#!/bin/bash
cmake -DANDROID_NDK=/opt/android-ndk -DANDROID_NATIVE_API_LEVEL=android-9 -DCMAKE_TOOLCHAIN_FILE=/home/rangeli/projects/android-cmake/toolchain/android.toolchain.cmake \
. -DCEGUI_BUILD_RENDERER_OPENGLES=TRUE -DCEGUI_STRING_CLASS=2 -DCMAKE_SKIP_RPATH=TRUE -DCEGUI_BUILD_XMLPARSER_TINYXML=TRUE \
-DCEGUI_BUILD_IMAGECODEC_TGA=TRUE -DCEGUI_BUILD_IMAGECODEC_FREEIMAGE=TRUE -DCEGUI_OPTION_DEFAULT_IMAGECODEC=FreeImageImageCodec -DCEGUI_BUILD_STATIC_CONFIGURATION=TRUE 
