#!/bin/bash

NDK_LOCATION=/opt/android-ndk/
ARM_ABI=armeabi-v7a
if [[ $1 ]] 
then 
    NDK_LOCATION=$1 
fi

if [[ $2 ]] 
then 
    ABI=$2 
fi

cmake -DANDROID_ABI=$ABI -DCMAKE_TOOLCHAIN_FILE=./toolchain/android.toolchain.cmake -DANDROID_NDK=$NDK_LOCATION -DANDROID_NATIVE_API_LEVEL=android-9 \
-DCEGUI_BUILD_RENDERER_OPENGLES=TRUE -DCEGUI_STRING_CLASS=2 -DCMAKE_SKIP_RPATH=TRUE -DCEGUI_BUILD_XMLPARSER_TINYXML=TRUE \
-DCEGUI_BUILD_IMAGECODEC_TGA=TRUE -DCEGUI_BUILD_IMAGECODEC_FREEIMAGE=TRUE -DCEGUI_OPTION_DEFAULT_IMAGECODEC=FreeImageImageCodec -DCEGUI_BUILD_STATIC_CONFIGURATION=TRUE .. 
